#ifndef DEF_CONSTANTE
#define DEF_CONSTANTE

#define FENETRE_LARGEUR 1152
#define FENETRE_HAUTEUR 960

#define FPS_LIMITE 16

#define TAILLE_ENNEMI 40
#define VITESSE_DEPLACEMENT_ENNEMI 5
#define Y_DEPART_ENNEMI_1 256
#define VIE_ENNEMI_1 100

#define TAILLE_TOURELLE 34
#define RAYON_DEPART_TOURELLE 150
#define VITESSE_D_ATTAQUE_TOURELLE_DEPART 1000 // == 1 tire par seconde

#endif